FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml README.md LICENSE ./
COPY config ./config
COPY apps ./apps
COPY workers ./workers
COPY packages ./packages

RUN pip install --no-cache-dir .

CMD ["python", "-m", "omnisaver_web"]
